image: fmanco/cpp-build


before_script:
    - apt-get update
    - apt-get install -y libxen-dev catch

stages:
    - build
    - test


build:
    stage: build
    script:
        - make
    tags:
        - docker

test:
    stage: test
    script:
        - make tests
        - ./test/run-catch
    tags:
        - docker
