image: fmanco/cpp-build


stages:
    - build
    - test


build:
    stage: build
    before_script:
        - apt-get update
        - apt-get install -y libxen-dev catch
    script:
        - make all
        - make tests
    artifacts:
        paths:
            - app/lixs
            - test/run-catch
    tags:
        - docker

test:
    stage: test
    before_script:
        - apt-get update
        - apt-get install -y libxen-[0-9].[0-9]
    script:
        - ./test/run-catch
    dependencies:
        - build
    tags:
        - docker
